---
name: run action from base PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  base_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
