---
name: run action from fork PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fork_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
